# Generated by Django 5.1.1 on 2025-05-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Основной текст поста'),
        ),
    ]
